kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: filebeat-config
  data:
    filebeat.yml: |
      filebeat.inputs:
      - type: log
        paths:
          - /home/log/*.log
        scan_frequency: 10s
        fields:
          doc_type: syslog
      output.logstash:
        hosts: ["52.81.54.233:30044"]
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: filebeat-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: filebeat
    template:
      metadata:
        labels:
          app: filebeat
      spec:
        containers:
        - image: docker.elastic.co/beats/filebeat:7.2.0
          name: filebeat
          args: [
           "-c","/home/filebeat-config/filebeat.yml",
           "-e",
          ]
          volumeMounts:
          - name: sys-log
            mountPath: /home/log
          - name: filebeat-config
            mountPath: /home/filebeat-config
        - image: ish2b/sentlog:latest
          name: sentlog
          volumeMounts: 
          - name: sys-log
            mountPath: /sentlog
        volumes:
          - name: sys-log
            emptyDir: {}
          - name: filebeat-config
            configMap:
              name: filebeat-config
